/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation(libs.com.google.code.gson.gson)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.com.squareup.okhttp3.okhttp)
    testImplementation(libs.com.squareup.okhttp3.logging.interceptor)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    testCompileOnly(libs.org.projectlombok.lombok)
    testAnnotationProcessor(libs.org.projectlombok.lombok)

    compileOnly(libs.org.jetbrains.annotations)
    annotationProcessor(libs.org.jetbrains.annotations)
    testCompileOnly(libs.org.jetbrains.annotations)
    testAnnotationProcessor(libs.org.jetbrains.annotations)
}

group = "me.knighthat"
version = "0.0.1"
description = "Unofficial YouTube's Innertube API Written in Java"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
